### ISSUE TITLE
What is the license of the dataset?

### ISSUE THREAD

**Issue by dmlls** [teemuvh/antonym-substitution#1]
Hi @teemuvh.

First off, thank you and your colleagues for this great dataset.

I wanted to ask, what is the license of the dataset?

We are working on a paper that introduces a negation-focused dataset (see https://github.com/dmlls/cannot-dataset), and are planning to release it under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Since our dataset contains samples from your dataset, we want to make sure we respect its license.

**Comment by teemuvh** [comment]
Hi! The dataset goes by the CC BY-NC license so you should be free to use it for your paper. Looking forward to seeing more negation work!
